import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from alpha_vantage.timeseries import TimeSeries
import datetime

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(page_title="TSX AI Portfolio Manager", layout="wide", page_icon="💰")

# --- 2. HIGH-VISIBILITY PROFESSIONAL THEME ---
st.markdown("""
    <style>
    .stApp { background-color: #FFFFFF; }
    h1, h2, h3, p, span, label { color: #0a192f !important; }
    
    /* Modern Metric Cards */
    div[data-testid="stMetric"] {
        background-color: #ffffff;
        border: 1px solid #e0e0e0;
        padding: 20px;
        border-radius: 12px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
    }
    
    /* Table Styling */
    .stTable { 
        background-color: #ffffff; 
        border-radius: 10px;
        border: 1px solid #dee2e6;
    }
    </style>
    """, unsafe_allow_html=True)

# --- 3. HEADER ---
st.title("📈 TSX AI Investment Trainer")
st.caption(f"Portfolio Tracking & Strategy Analysis | Last Updated: {datetime.datetime.now().strftime('%Y-%m-%d')}")

# --- 4. DATA LOADING ---
def load_data():
    try:
        # Load the trade analysis generated by bot.py
        df = pd.read_csv("trades.csv")
        return df
    except:
        return None

data = load_data()

# --- 5. TOP PERFORMANCE METRICS ---
col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Total Virtual Capital", "$100,000.00", "CAD")

with col2:
    if data is not None and 'P&L_%' in data.columns:
        avg_pnl = data['P&L_%'].mean()
        st.metric("Strategy Performance", f"{avg_pnl:.2f}%", f"{avg_pnl:.2f}%")
    else:
        st.metric("Strategy Performance", "0.00%", "Waiting for data")

with col3:
    active_buys = len(data[data['Signal'] == 'BUY']) if data is not None else 0
    st.metric("Active Buy Signals", active_buys)

st.divider()

# --- 6. LIVE P&L LEDGER (The Trainer) ---
if data is not None:
    st.subheader("🤖 Strategy Ledger & Profit/Loss Analysis")
    st.info("The AI uses these results to 'learn' which signals provide the highest returns.")
    
    def style_pnl(val):
        if isinstance(val, (int, float)):
            if val > 0: return 'color: #008148; font-weight: bold;' # Profit Green
            if val < 0: return 'color: #d90429; font-weight: bold;' # Loss Red
        return 'color: #0a192f;'

    # Clean up and display columns
    cols_to_show = ['Name', 'Ticker', 'Price', 'Signal', 'Bought_At', 'P&L_%']
    display_df = data[cols_to_show]
    
    try:
        styled_table = display_df.style.map(style_pnl, subset=['P&L_%'])
    except AttributeError:
        styled_table = display_df.style.applymap(style_pnl, subset=['P&L_%'])
        
    st.table(styled_table)
else:
    st.warning("⚠️ **Ledger not found.** Please run your GitHub Action to generate 'trades.csv'.")

# --- 7. DEEP DIVE TREND ANALYSIS ---
st.divider()
st.subheader("📊 High-Precision Trend Charting")

AV_API_KEY = "UG99FWTXZTMOSVFD" 

@st.cache_data(ttl=3600)
def get_chart(ticker):
    try:
        av_ticker = ticker.replace(".TO", ".TRT")
        ts = TimeSeries(key=AV_API_KEY, output_format='pandas')
        chart_data, _ = ts.get_daily(symbol=av_ticker)
        chart_data.columns = ['Open', 'High', 'Low', 'Close', 'Volume']
        return chart_data.head(60)
    except:
        return None

selected = st.selectbox("Select a stock for detailed analysis:", ["SHOP.TO", "RY.TO", "ENB.TO", "VET.TO", "CSU.TO"])

if selected:
    with st.spinner('Syncing with market data...'):
        history = get_chart(selected)
    
    if history is not None and not history.empty:
        fig = go.Figure(data=[go.Candlestick(
            x=history.index,
            open=history['Open'],
            high=history['High'],
            low=history['Low'],
            close=history['Close'],
            increasing_line_color='#008148', 
            decreasing_line_color='#d90429'
        )])
        fig.update_layout(
            template="plotly_white",
            height=500,
            xaxis_rangeslider_visible=False,
            margin=dict(l=10, r=10, t=10, b=10)
        )
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.error("Live charting limit reached. Please check back in a few minutes.")
